### ISSUE TITLE
Drop Truffle, replace with something else

### ISSUE THREAD

**Issue by HarryR** [HarryR/ethsnarks-miximus#6]
Truffle seems to frequently break in really really dumb ways.

Candidates to replace truffle:

 * https://github.com/embark-framework/embark (JS based)

**Comment by barryWhiteHat** [comment]
Some alternatives are 
https://medium.com/limechain/etherlime-framework-8cbb270944d6
and 
https://medium.com/nomic-labs-blog/towards-a-mature-ecosystem-of-ethereum-developer-tools-bdff10e6cdc3

**Comment by HarryR** [comment]
```
     Error: Returned error: Key not found in database
      at Object.ErrorResponse (/Users/nomad/Projects/ethsnarks/node_modules/truffle/build/webpack:/~/web3-core-requestmanager/~/web3-core-helpers/src/errors.js:29:1)
      at /Users/nomad/Projects/ethsnarks/node_modules/truffle/build/webpack:/~/web3-core-requestmanager/src/index.js:140:1
      at /Users/nomad/Projects/ethsnarks/node_modules/truffle/build/webpack:/packages/truffle-provider/wrapper.js:112:1
      at XMLHttpRequest.request.onreadystatechange (/Users/nomad/Projects/ethsnarks/node_modules/truffle/build/webpack:/~/web3-providers-http/src/index.js:96:1)
      at XMLHttpRequestEventTarget.dispatchEvent (/Users/nomad/Projects/ethsnarks/node_modules/truffle/build/webpack:/~/xhr2-cookies/dist/xml-http-request-event-target.js:34:1)
      at XMLHttpRequest._setReadyState (/Users/nomad/Projects/ethsnarks/node_modules/truffle/build/webpack:/~/xhr2-cookies/dist/xml-http-request.js:208:1)
      at XMLHttpRequest._onHttpResponseEnd (/Users/nomad/Projects/ethsnarks/node_modules/truffle/build/webpack:/~/xhr2-cookies/dist/xml-http-request.js:318:1)
      at IncomingMessage.<anonymous> (/Users/nomad/Projects/ethsnarks/node_modules/truffle/build/webpack:/~/xhr2-cookies/dist/xml-http-request.js:289:47)
      at endReadableNT (_stream_readable.js:1129:12)
      at processTicksAndRejections (internal/process/next_tick.js:76:17)
```

Yes Truffle, \*pats head\* good job, thank you, an error happened... Now, if only you could tell me what caused it? No, that's too difficult...

Using Truffle, and NodeJS in general, is like dealing with a passive aggressive waiter at a restaurant who, when asked for anything on the menu, sneers at you for wanting something that they obviously can't serve for reasons which are so obtusely unfathomable.

> Me: Can I have a steak
> Truffle: ERROR OIL TEMPERATURE EXCEEDS UNKNOWN LIMITS
> Me: uhh, this is a steak house!
> Truffle: WHY ARE YOU LOOKING AT ME, CANT YOU SEE I DON'T WORK HERE
> Me: this is a restaurant? rite...
> Truffle: ASYNC HANDLER CHAIN INVALID
> Me: ......
